### ISSUE TITLE
Some composer packages might require ssh

### ISSUE THREAD

**Issue by heisfer** [swiftotter/den#159]
**Is your feature request related to a problem? Please describe.**
As the title said

**Describe the solution you'd like**
No idea if this is ideal but adding .env option ssh key location if needed

like SSH_KEY=~/.ssh/id_rsa  or absolute path /home/user/.ssh/id_rsa
AFAIK only private key is needed.
or 
SSH_KEY_PRIVATE=
SSH_KEY_PUBLIC=
or just ditch the key part

**Comment by bap14** [comment]
Do you have an example of composer packages that require SSH keys? Is this during `composer require` or during the normal execution of the library the script is expecting an SSH key to be available but isn't? Just want to make sure that if it's decided to include this we have a test case to use.

In the meantime you could use a custom `my_project/.warden/warden-env.yml` file to mount your SSH keys:

*my_project/.warden/warden-env.yml*
```yaml
version: "3.5"
service:
  php-fpm:
    volumes:
      - /Users/bap14/.ssh/id_rsa:/var/www/.ssh/id_rsa
  php-debug:
    volumes:
      - /Users/bap14/.ssh/id_rsa:/var/www/.ssh/id_rsa
```
