### ISSUE TITLE
ssh-agent - Error connecting to agent: No such file or directory

### ISSUE THREAD

**Issue by dudzio12** [swiftotter/den#180]
**Version of Den**
1.0.0-beta.13

**Image**
`den-php-fpm-magento2:7.4-node10`

**Describe the bug**
I'm using ssh-agent forwarding from my local machine (macOS 13.1). 

This is my local `~/.ssh/config` file.

```
Host *
    AddKeysToAgent yes
    UseKeychain yes
    ForwardAgent yes
    IdentityFile ~/.ssh/id_rsa
```

    
**To Reproduce**
1.  Prepare local ssh config:
 `~/.ssh/config`:
 
```
Host *
    AddKeysToAgent yes
    UseKeychain yes
    ForwardAgent yes
    IdentityFile ~/.ssh/id_rsa
```
2. Run `ssh-add -l` locally (should return your local ssh key).
3. Get onto den shell
4. Run `ssh-add -l`
 This should list the same ssh key, but it returns:
 `Error connecting to agent: No such file or directory`
 
**Expected behavior**
`ssh-add -l` - should use the same ssh-agent with the same key as on local env.

**Additional context**

Running `echo $SSH_AUTH_SOCK` from den shell returns:
`/tmp/ssh-auth.sock`
This file doesn't exists, that's the first problem.
You should use `/run/host-services/ssh-auth.sock`, since that file exists.
`/run/host-services/ssh-auth.sock` - is owned by root, that's the second problem.

Running:
`export SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock`
then:
`sudo chown www-data: /run/host-services/ssh-auth.sock`
fixes the issue. `ssh-add -l` returns my local key and I can successfully use my local key to authorize.

**Comment by dudzio12** [comment]
This is related to https://github.com/wardenenv/warden/issues/318

Adding this to `warden-env.yml` fixes the issue:

```
version: "3.5"

services:
  php-fpm:
    build:
      context: ./.warden/php-fpm
    environment:
      SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
  php-debug:
    build:
      context: ./.warden/php-debug
    environment:
      SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
```
