### ISSUE TITLE
Determine if VirtioFS is fast enough to drop Mutagen 

### ISSUE THREAD

**Issue by navarr** [swiftotter/den#4]

**Comment by ihor-sviziev** [comment]
hi @navarr,
I did some investigation on our pretty big M2 project (605 composer packages):
- MacOS 12.4
- Docker 4.9.1
-- Enabled Use the new Virtualization framework
-- Enabled Enable VirtioFS accelerated directory sharing



## Using VirtioFS instead Mutagen:
### What's changed:
- /opt/homebrew/Cellar/warden/0.12.0/environments/magento2/magento2.darwin.yml
```
version: "3.5"

x-volumes: &volumes
  - .${WARDEN_WEB_ROOT:-}/pub/media:/var/www/html/pub/media:cached
#  - appdata:/var/www/html

x-environment: &environment
  - CHOWN_DIR_LIST=pub/media ${CHOWN_DIR_LIST:-}

services:
  nginx: { volumes: *volumes }
  php-fpm: { volumes: *volumes, environment: *environment }
  php-debug: { volumes: *volumes, environment: *environment }

#volumes:
#  appdata:
```
- /opt/homebrew/Cellar/warden/0.12.0/commands/env.cmd
-- Replaced all `warden sync...` to `echo warden sync...` command to not start mutagen session
- Terminated all mutagen sessions 
```
➜  ~ mutagen sync list
--------------------------------------------------------------------------------
No synchronization sessions found
--------------------------------------------------------------------------------
```


## Result with VitrioFS
```
composer install - 1m58.102s
rm -Rf ./vendor/* - 0m35.767s
```

## Result with Mutagen (no changes)
```
composer install - 0m18.313s
rm -Rf ./vendor/* - 0m1.318s
```


|                                  | Mutagen           | VirtioFS mount | Diff                                      |
| ------------------- |          --------- | --------------- | -------------------------- |
| `composer install` | 0m18.313s | 1m58.102s        | **~6.45x/100sec slower** |
| `rm -Rf ./vendor/*` | 0m1.318s | 0m35.767s         |  **~27x/34sec slower**.     |
